import { NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import MarkdownIt from 'markdown-it';

const md = new MarkdownIt({
  html: true,
  breaks: true,
  linkify: true
});

const execAsync = promisify(exec);

async function callGeminiDirectAPI(prompt: string) {
  const response = await fetch(
    `https://gateway.helicone.ai/v1beta/models/gemini-pro:generateContent?key=${process.env.GOOGLE_GENERATIVE_API_KEY}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Helicone-Auth': `Bearer ${process.env.HELICONE_API_KEY}`,
        'Helicone-Target-URL': 'https://generativelanguage.googleapis.com'
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }]
          }
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
          stopSequences: []
        }
      })
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API request failed: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text;
}

async function callOpenRouterAPI(prompt: string, model: string) {
  console.log('Calling OpenRouter API with model:', model);
  
  const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
      'X-Title': 'LegalFlow'
    },
    body: JSON.stringify({
      model: model,
      messages: [
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 2048
    })
  });

  const data = await response.json();
  console.log('OpenRouter API Response:', JSON.stringify(data, null, 2));

  if (!response.ok) {
    console.error('OpenRouter API Error:', data);
    throw new Error(`OpenRouter API request failed: ${response.status} ${response.statusText} - ${data.error?.message || 'Unknown error'}`);
  }

  const content = data.choices?.[0]?.message?.content;
  if (!content) {
    console.error('No content in OpenRouter response:', data);
    throw new Error('No content in OpenRouter response');
  }

  return content;
}

export async function POST(req: Request) {
  try {
    const { settings, templateText } = await req.json();
    console.log('Received request with settings:', settings);

    // If template is provided as a .docx file, convert it to plaintext using pandoc
    let context = templateText;
    if (settings.templateFile && settings.templateFile.endsWith('.docx')) {
      const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'template-'));
      const inputPath = path.join(tempDir, 'input.docx');
      const outputPath = path.join(tempDir, 'output.txt');
      
      await fs.writeFile(inputPath, Buffer.from(settings.templateFile, 'base64'));
      await execAsync(`pandoc "${inputPath}" -f docx -t plain -o "${outputPath}"`);
      context = await fs.readFile(outputPath, 'utf-8');
      await fs.rm(tempDir, { recursive: true });
    }

    const prompt = `
      You are a legal document drafting assistant. Using the following template as reference:
      
      ${context || 'No template provided'}
      
      Please draft a ${settings.agreement} with the following details:
      - Company: ${settings.companyName || 'Not specified'}
      - Contact: ${settings.contactPerson || 'Not specified'}
      
      Additional Instructions:
      ${settings.instructions || 'No additional instructions'}
      
      Important: Generate the document in plain text format only. Do not include any XML, HTML, or formatting tags.
      Please maintain a formal legal writing style and ensure all necessary clauses are included.
    `;

    try {
      let generatedContent;
      
      if (settings.apiType === 'google') {
        generatedContent = await callGeminiDirectAPI(prompt);
      } else if (settings.apiType === 'openrouter') {
        generatedContent = await callOpenRouterAPI(prompt, settings.model);
      } else {
        throw new Error('Invalid API type specified');
      }

      if (!generatedContent) {
        throw new Error('No content generated by the API');
      }

      const cleanContent = generatedContent
        .replace(/<[^>]*>/g, '')
        .trim();

      const htmlContent = md.render(cleanContent);

      console.log('Final HTML Content:', htmlContent);
      return NextResponse.json({ content: htmlContent });
    } catch (apiError) {
      console.error('API Error:', apiError);
      throw new Error(apiError instanceof Error ? apiError.message : 'API request failed');
    }
  } catch (error) {
    console.error('Error in draft API:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate document' },
      { status: 500 }
    );
  }
} 