import { NextResponse } from 'next/server';
import { OpenAI } from 'openai';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { promisify } from 'util';
import { exec } from 'child_process';
import MarkdownIt from 'markdown-it';

const execAsync = promisify(exec);
const md = new MarkdownIt();

async function callOpenAIAPI(prompt: string, model: string) {
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY || '',
  });

  const completion = await openai.chat.completions.create({
    model: model === 'gpt-4o' ? 'gpt-4' : model,
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    temperature: 0.7,
    max_tokens: 2048
  });

  const content = completion.choices[0]?.message?.content;
  if (!content) {
    throw new Error('No content in OpenAI response');
  }

  return content;
}

export async function POST(req: Request) {
  try {
    const { settings, templateText } = await req.json();
    console.log('Received request with settings:', settings);

    // If template is provided as a .docx file, convert it to plaintext using pandoc
    let context = templateText;
    if (settings.templateFile && settings.templateFile.endsWith('.docx')) {
      const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'template-'));
      const inputPath = path.join(tempDir, 'input.docx');
      const outputPath = path.join(tempDir, 'output.txt');
      
      await fs.writeFile(inputPath, Buffer.from(settings.templateFile, 'base64'));
      await execAsync(`pandoc "${inputPath}" -f docx -t plain -o "${outputPath}"`);
      context = await fs.readFile(outputPath, 'utf-8');
      await fs.rm(tempDir, { recursive: true });
    }

    const prompt = `
      You are a legal document drafting assistant. Using the following template as reference:
      
      ${context || 'No template provided'}
      
      Please draft a ${settings.agreement} with the following details:
      - Company: ${settings.companyName || 'Not specified'}
      - Contact: ${settings.contactPerson || 'Not specified'}
      
      Additional Instructions:
      ${settings.instructions || 'No additional instructions'}
      
      Important: Generate the document in plain text format only. Do not include any XML, HTML, or formatting tags.
      Please maintain a formal legal writing style and ensure all necessary clauses are included.
    `;

    try {
      const model = settings.model || 'gpt-3.5-turbo';
      const generatedContent = await callOpenAIAPI(prompt, model);

      if (!generatedContent) {
        throw new Error('No content generated by the API');
      }

      const cleanContent = generatedContent
        .replace(/<[^>]*>/g, '')
        .trim();

      const htmlContent = md.render(cleanContent);

      console.log('Final HTML Content:', htmlContent);
      return NextResponse.json({ content: htmlContent });
    } catch (apiError) {
      console.error('API Error:', apiError);
      throw new Error(apiError instanceof Error ? apiError.message : 'API request failed');
    }
  } catch (error) {
    console.error('Error in draft API:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate document' },
      { status: 500 }
    );
  }
} 