import { NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import MarkdownIt from 'markdown-it';

const md = new MarkdownIt({
  html: true,
  breaks: true,
  linkify: true
});

const execAsync = promisify(exec);
const MODEL_ID = "gemini-2.0-flash";
const GENERATE_CONTENT_API = "generateContent";

export async function POST(req: Request) {
  try {
    const { settings, templateText } = await req.json();
    console.log('Received request with settings:', settings);

    // If template is provided as a .docx file, convert it to plaintext using pandoc
    let context = templateText;
    if (settings.templateFile && settings.templateFile.endsWith('.docx')) {
      const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'template-'));
      const inputPath = path.join(tempDir, 'input.docx');
      const outputPath = path.join(tempDir, 'output.txt');
      
      await fs.writeFile(inputPath, Buffer.from(settings.templateFile, 'base64'));
      
      await execAsync(`pandoc "${inputPath}" -f docx -t plain -o "${outputPath}"`);
      context = await fs.readFile(outputPath, 'utf-8');
      
      // Clean up temp files
      await fs.rm(tempDir, { recursive: true });
    }

    // Prepare the prompt for the model
    const prompt = `
      You are a legal document drafting assistant. Using the following template as reference:
      
      ${context || 'No template provided'}
      
      Please draft a ${settings.agreement} with the following details:
      - Company: ${settings.companyName || 'Not specified'}
      - Contact: ${settings.contactPerson || 'Not specified'}
      
      Additional Instructions:
      ${settings.instructions || 'No additional instructions'}
      
      Important: Generate the document in plain text format only. Do not include any XML, HTML, or formatting tags.
      Please maintain a formal legal writing style and ensure all necessary clauses are included.
    `;

    try {
      // Call Gemini API
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_ID}:${GENERATE_CONTENT_API}?key=${process.env.GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [
              {
                role: "user",
                parts: [{ text: prompt }]
              }
            ],
            generationConfig: {
              temperature: 0.7,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 2048,
              stopSequences: []
            }
          })
        }
      );

      console.log('Gemini API Response Status:', response.status);
      const data = await response.json();
      console.log('Gemini API Response Data:', JSON.stringify(data, null, 2));

      if (!response.ok) {
        throw new Error(`Gemini API request failed: ${response.status} ${response.statusText}`);
      }

      // Extract content from the response
      const generatedContent = data.candidates?.[0]?.content?.parts?.[0]?.text;
      console.log('Raw Generated Content:', generatedContent);

      if (!generatedContent) {
        console.error('No content in Gemini response:', data);
        throw new Error('No content generated by Gemini API');
      }

      // Clean the content to ensure it's plain text
      const cleanContent = generatedContent
        .replace(/<[^>]*>/g, '') // Remove any HTML/XML tags
        .trim();

      // Convert markdown to HTML for better presentation
      const htmlContent = md.render(cleanContent);

      console.log('Final HTML Content:', htmlContent);
      return NextResponse.json({ content: htmlContent });
    } catch (geminiError) {
      console.error('Gemini API Error:', geminiError);
      throw new Error(geminiError instanceof Error ? geminiError.message : 'Gemini API request failed');
    }
  } catch (error) {
    console.error('Error in draft API:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate document' },
      { status: 500 }
    );
  }
} 